name: Clang-Format
on:
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: "Extra Resolve Options"
        required: false
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
jobs:
  name: ClangFormat
    runs-on: [self-hosted, docker]
    container:
      image: fifty2technology/clang-format
      options: --user 0:0
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Run Clang-format
        run: clang-format --help
      - name: Run Clang-format
        run: clang-format -version
      - name: Run Clang-format
        run: find ./ -iname *.hpp -o -iname *.cpp -o -iname *.c -o -iname *.h | xargs clang-format --dry-run --Werror
